version: '3.7'
services:
    frontend:
        container_name: 'Frontend'
        image: node:15.3.0
        command: npm run docker
        volumes:
            - ./frontend:/usr/src/app
        working_dir: /usr/src/app
        ports:
            - '3000:3000'
        environment:
            HOST: 0.0.0.0
    server:
        container_name: 'Server'
        image: node:15.3.0
        command: npm run docker
        volumes:
            - ./server:/usr/src/app
        working_dir: /usr/src/app
        ports:
            - '4000:4000'
